title: Mushroom Number
views:
  - title: Number
    icon: mdi:numeric
    cards:
      - type: grid
        title: Basic
        cards:
          - type: custom:mushroom-dev-number-card
            entity: input_number.percentage
        columns: 2
        square: false
